export function getHtmlPage(): string {
  return [
    ko('!DOCTYPE html'),
    '<html lang="zh-CN">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">',
    '<title>RAG Chatbot</title>',
    '<link rel="manifest" href="/manifest.json">',
    '<meta name="theme-color" content="#0d9488">',
    '<meta name="apple-mobile-web-app-capable" content="yes">',
    '<meta name="apple-mobile-web-app-status-bar-style" content="default">',
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '<link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600;6..72,700&family=Work+Sans:wght@400;500;600&display=swap" rel="stylesheet">',
    '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">',
    '<script src="https://cdn.jsdelivr.net/npm/marked@15/marked.min.js"></script>',
    '<style>',
    ':root{--primary:#0d9488;--primary-hover:#0f766e;--primary-light:#ccfbf1;--sidebar-bg:#f5f2ed;--sidebar-width:320px;--chat-bg:#faf8f5;--text-primary:#1c1917;--text-secondary:#78716c;--border:#e7e5e4;--bubble-user:#0d9488;--bubble-user-text:#fff;--bubble-bot:#f0ece6;--bubble-bot-text:#1c1917;--hover-bg:#e7e5e4;--radius:12px;--header-h:56px;--font-heading:\'Newsreader\',Georgia,serif;--font-body:\'Work Sans\',system-ui,sans-serif}',
    '.dark{--sidebar-bg:#1c1917;--chat-bg:#1c1917;--text-primary:#e7e5e4;--text-secondary:#a8a29e;--border:#44403c;--bubble-bot:#292524;--bubble-bot-text:#e7e5e4;--hover-bg:#292524}',
    '*{box-sizing:border-box;margin:0;padding:0}',
    'body{font-family:var(--font-body);background:var(--chat-bg);color:var(--text-primary);height:100vh;overflow:hidden;display:flex;transition:background .3s,color .3s}',
    '',
    '/* Sidebar */',
    '#sidebar{width:var(--sidebar-width);min-width:var(--sidebar-width);background:var(--sidebar-bg);border-right:1px solid var(--border);display:flex;flex-direction:column;height:100vh;z-index:100}',
    '.sidebar-header{display:flex;align-items:center;justify-content:space-between;padding:16px;border-bottom:1px solid var(--border)}',
    '.sidebar-header h2{font-family:var(--font-heading);font-size:18px;font-weight:600;letter-spacing:-.3px}',
    '.sidebar-header .close-btn{display:none;background:none;border:none;font-size:24px;color:var(--text-secondary);cursor:pointer}',
    '.search-box{margin:12px 16px;padding:10px 12px;border:1px solid var(--border);border-radius:10px;background:var(--chat-bg);display:flex;align-items:center;gap:8px}',
    '.search-box input{flex:1;border:none;outline:none;background:transparent;color:var(--text-primary);font-size:14px;font-family:var(--font-body)}',
    '.search-box input::placeholder{color:var(--text-secondary)}',
    '.search-box i{color:var(--text-secondary)}',
    '.new-chat-btn{display:flex;align-items:center;gap:8px;margin:0 16px 12px;padding:10px 16px;background:var(--primary);color:#fff;border:none;border-radius:10px;cursor:pointer;font-size:14px;font-weight:500;font-family:var(--font-body);transition:background .2s}',
    '.new-chat-btn:hover{background:var(--primary-hover)}',
    '#conv-list{flex:1;overflow-y:auto;padding:0 16px}',
    '.conv-item{padding:12px 12px;border-radius:8px;cursor:pointer;transition:background .2s;position:relative;margin-bottom:2px}',
    '.conv-item:hover{background:var(--hover-bg)}',
    '.conv-item.active{background:var(--primary-light);color:var(--primary-dark);font-weight:500}',
    '.conv-item .conv-title{font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:220px}',
    '.conv-item .conv-time{font-size:11px;color:var(--text-secondary);margin-top:4px}',
    '.conv-item .conv-actions{display:none;position:absolute;right:8px;top:8px;gap:4px}',
    '.conv-item:hover .conv-actions{display:flex}',
    '.conv-actions button{background:var(--hover-bg);border:none;border-radius:4px;padding:4px 6px;cursor:pointer;font-size:12px;color:var(--text-secondary);transition:color .2s}',
    '.conv-actions button:hover{color:var(--primary)}',
    '',
    '#overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.3);z-index:99}',
    '',
    '#main{flex:1;display:flex;flex-direction:column;height:100vh;min-width:0}',
    '.chat-header{display:flex;align-items:center;gap:12px;padding:0 20px;height:var(--header-h);border-bottom:1px solid var(--border);background:var(--chat-bg);flex-shrink:0}',
    '.chat-header .menu-btn{display:none;background:none;border:none;font-size:24px;color:var(--text-primary);cursor:pointer;padding:4px}',
    '.chat-header .chat-title{flex:1;font-size:16px;font-weight:600;font-family:var(--font-heading);letter-spacing:-.2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
    '.chat-header .header-actions{display:flex;gap:8px}',
    '.chat-header .header-actions button{background:none;border:1px solid var(--border);border-radius:8px;padding:6px 12px;font-size:13px;color:var(--text-secondary);cursor:pointer;transition:all .2s;display:flex;align-items:center;gap:6px;font-family:var(--font-body)}',
    '.chat-header .header-actions button:hover{background:var(--hover-bg);color:var(--primary)}',
    '',
    '#messages{flex:1;overflow-y:auto;padding:24px 20px;display:flex;flex-direction:column;gap:16px;-webkit-overflow-scrolling:touch}',
    '.message{display:flex;max-width:80%;animation:fadeIn .3s}',
    '.message.user{align-self:flex-end}',
    '.message.assistant{align-self:flex-start}',
    ' .message .bubble{padding:12px 18px;border-radius:var(--radius);line-height:1.6;font-size:14px;word-break:break-word;position:relative}',
    '.message.user .bubble{background:var(--bubble-user);color:var(--bubble-user-text);border-radius:var(--radius) var(--radius) 4px var(--radius)}',
    '.message.assistant .bubble{background:var(--bubble-bot);color:var(--bubble-bot-text);border-radius:var(--radius) var(--radius) var(--radius) 4px}',
    '@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}',
    '.message .bubble pre{background:#1c1917;color:#e7e5e4;padding:12px;border-radius:8px;overflow-x:auto;font-size:13px;margin:8px 0}',
    '.message .bubble code{font-family:\'SF Mono\',Monaco,\'Cascadia Code\',monospace;font-size:13px}',
    '.message .bubble p{margin:6px 0}',
    '.message .bubble ul,.message .bubble ol{padding-left:20px;margin:6px 0}',
    '.message .bubble table{border-collapse:collapse;margin:8px 0;width:100%;font-size:13px}',
    '.message .bubble th,.message .bubble td{border:1px solid var(--border);padding:6px 10px;text-align:left}',
    '.message .bubble th{background:var(--hover-bg);font-weight:600}',
    '.message .bubble blockquote{border-left:3px solid var(--primary);padding-left:12px;margin:8px 0;color:var(--text-secondary)}',
    '.welcome-msg{text-align:center;color:var(--text-secondary);margin:auto;padding:40px 20px}',
    '.welcome-msg h1{font-family:var(--font-heading);font-size:32px;margin-bottom:12px;color:var(--text-primary);font-weight:700;letter-spacing:-.5px}',
    '.welcome-msg p{font-size:14px;line-height:1.8}',
    '.welcome-msg .suggestions{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;margin-top:20px}',
    '.welcome-msg .suggestions button{background:var(--bubble-bot);border:1px solid var(--border);border-radius:20px;padding:8px 18px;font-size:13px;color:var(--text-primary);cursor:pointer;transition:all .2s;font-family:var(--font-body)}',
    '.welcome-msg .suggestions button:hover{border-color:var(--primary);color:var(--primary)}',
    '',
    '.typing{display:flex;gap:5px;padding:4px 0}',
    '.typing span{width:7px;height:7px;background:var(--text-secondary);border-radius:50%;animation:bounce 1.4s infinite}',
    '.typing span:nth-child(2){animation-delay:.2s}',
    '.typing span:nth-child(3){animation-delay:.4s}',
    '@keyframes bounce{0%,60%,100%{transform:translateY(0)}30%{transform:translateY(-5px)}}',
    '',
    '#input-area{flex-shrink:0;padding:16px 20px;padding-bottom:calc(16px + env(safe-area-inset-bottom,0px));border-top:1px solid var(--border);background:var(--chat-bg)}',
    '.input-row{display:flex;gap:12px;align-items:flex-end}',
    '#input-area textarea{flex:1;border:1px solid var(--border);border-radius:12px;padding:12px 16px;font-size:14px;font-family:var(--font-body);outline:none;resize:none;max-height:150px;background:var(--sidebar-bg);color:var(--text-primary);transition:border-color .2s;line-height:1.5}',
    '#input-area textarea:focus{border-color:var(--primary)}',
    '#input-area textarea::placeholder{color:var(--text-secondary)}',
    '#send-btn{width:44px;height:44px;border-radius:50%;background:var(--primary);color:#fff;border:none;cursor:pointer;font-size:18px;display:flex;align-items:center;justify-content:center;transition:background .2s;flex-shrink:0}',
    '#send-btn:hover{background:var(--primary-hover)}',
    '#send-btn:disabled{opacity:.5;cursor:not-allowed}',
    '',
    '#notification-container{position:fixed;top:16px;left:50%;transform:translateX(-50%);z-index:9999;display:flex;flex-direction:column;gap:8px;pointer-events:none}',
    '.notification{padding:10px 20px;border-radius:10px;font-size:13px;font-family:var(--font-body);box-shadow:0 4px 12px rgba(0,0,0,.1);transition:all .3s;opacity:0;transform:translateY(-12px);pointer-events:auto;white-space:nowrap}',
    '.notification.show{opacity:1;transform:translateY(0)}',
    '.notification.info{background:#fff;color:var(--text-primary);border:1px solid var(--border)}',
    '.notification.success{background:#0d9488;color:#fff}',
    '.notification.error{background:#dc2626;color:#fff}',
    '.dark .notification.info{background:#292524;border-color:#44403c}',
    '',
    '.modal-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:200;align-items:center;justify-content:center}',
    '.modal-overlay.show{display:flex}',
    '.modal{background:var(--chat-bg);border-radius:16px;width:90%;max-width:600px;max-height:80vh;display:flex;flex-direction:column;box-shadow:0 20px 60px rgba(0,0,0,.3)}',
    '.modal-header{display:flex;align-items:center;justify-content:space-between;padding:20px;border-bottom:1px solid var(--border)}',
    '.modal-header h2{font-size:18px;font-family:var(--font-heading)}',
    '.modal-header .close-btn{background:none;border:none;font-size:24px;color:var(--text-secondary);cursor:pointer}',
    '.modal-body{flex:1;overflow-y:auto;padding:20px}',
    '.modal-footer{padding:16px 20px;border-top:1px solid var(--border);display:flex;gap:12px}',
    '.modal-footer button{padding:10px 20px;border-radius:8px;font-size:14px;font-family:var(--font-body);cursor:pointer;transition:all .2s}',
    '.btn-primary{background:var(--primary);color:#fff;border:none}',
    '.btn-primary:hover{background:var(--primary-hover)}',
    '.btn-outline{background:transparent;border:1px solid var(--border);color:var(--text-primary)}',
    '.btn-outline:hover{background:var(--hover-bg)}',
    '',
    '.doc-list{display:flex;flex-direction:column;gap:8px}',
    '.doc-item{display:flex;align-items:center;justify-content:space-between;padding:12px;border:1px solid var(--border);border-radius:8px;transition:background .2s}',
    '.doc-item:hover{background:var(--hover-bg)}',
    '.doc-item .doc-info{flex:1;min-width:0}',
    '.doc-item .doc-name{font-size:14px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
    '.doc-item .doc-meta{font-size:12px;color:var(--text-secondary);margin-top:2px}',
    '.doc-item .doc-del{background:none;border:none;color:#dc2626;cursor:pointer;font-size:18px;padding:4px}',
    '.doc-loading{display:flex;align-items:center;gap:10px;padding:16px;border:1px dashed var(--border);border-radius:8px;color:var(--text-secondary);font-size:13px;animation:pulse 1.5s infinite}',
    '.doc-loading .spinner{width:18px;height:18px;border:2px solid var(--border);border-top-color:var(--primary);border-radius:50%;animation:spin .8s linear infinite}',
    '@keyframes spin{to{transform:rotate(360deg)}}',
    '@keyframes pulse{0%,100%{opacity:1}50%{opacity:.6}}',
    '',
    '.rename-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:300;align-items:center;justify-content:center}',
    '.rename-overlay.show{display:flex}',
    '.rename-box{background:var(--chat-bg);border-radius:12px;padding:24px;width:90%;max-width:380px;box-shadow:0 20px 60px rgba(0,0,0,.3)}',
    '.rename-box h3{margin-bottom:12px;font-size:16px;font-family:var(--font-heading)}',
    '.rename-box input{width:100%;padding:10px 12px;border:1px solid var(--border);border-radius:8px;font-size:14px;font-family:var(--font-body);background:var(--sidebar-bg);color:var(--text-primary);outline:none;margin-bottom:12px}',
    '.rename-box input:focus{border-color:var(--primary)}',
    '.rename-box .rename-btns{display:flex;gap:8px;justify-content:flex-end}',
    '.rename-box .rename-btns button{padding:8px 16px;border-radius:6px;font-size:13px;cursor:pointer;font-family:var(--font-body)}',
    '',
    '.confirm-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:400;align-items:center;justify-content:center}',
    '.confirm-overlay.show{display:flex}',
    '.confirm-box{background:var(--chat-bg);border-radius:12px;padding:24px;width:90%;max-width:360px;box-shadow:0 20px 60px rgba(0,0,0,.3)}',
    '.confirm-box p{margin-bottom:20px;font-size:14px;line-height:1.6;color:var(--text-primary)}',
    '.confirm-box .confirm-btns{display:flex;gap:8px;justify-content:flex-end}',
    '.confirm-box .confirm-btns button{padding:8px 16px;border-radius:8px;font-size:13px;cursor:pointer;font-family:var(--font-body);transition:all .2s}',
    '',
    '@media(max-width:767px){',
    '#sidebar{position:fixed;left:0;top:0;transform:translateX(-100%);width:300px;z-index:100}',
    '#sidebar.open{transform:translateX(0)}',
    '.sidebar-header .close-btn{display:block}',
    '#overlay.show{display:block}',
    '.chat-header .menu-btn{display:block}',
    '.message{max-width:90%}',
    '#messages{padding:16px 12px}',
    '#input-area{padding:12px 12px}',
    '.chat-header{padding:0 12px}',
    '.chat-header .header-actions button span{display:none}',
    '}',
    '</style>',
    '</head>',
    '<body>',
    '<div id="overlay"></div>',
    '<div id="sidebar">',
    '  <div class="sidebar-header">',
    '    <h2>对话历史</h2>',
    '    <button class="close-btn" onclick="toggleSidebar()">&times;</button>',
    '  </div>',
    '  <div class="search-box">',
    '    <input type="text" id="search-input" placeholder="搜索对话..." oninput="filterConversations(this.value)">',
    '  </div>',
    '  <button class="new-chat-btn" onclick="newConversation()">新对话</button>',
    '  <div id="conv-list"></div>',
    '</div>',
    '<div id="main">',
    '  <div class="chat-header">',
    '    <button class="menu-btn" onclick="toggleSidebar()">&#9776;</button>',
    '    <div class="chat-title" id="chat-title">RAG Chatbot</div>',
    '    <div class="header-actions">',
    '      <button onclick="toggleDarkMode()">主题</button>',
    '      <button onclick="showKB()">知识库</button>',
    '    </div>',
    '  </div>',
    '  <div id="messages">',
    '    <div class="welcome-msg" id="welcome">',
    '      <h1>RAG Chatbot</h1>',
    '      <p>基于 DeepSeek-V4-Flash + Qwen3-VL-Embedding 的智能助手<br>支持知识库检索、流式回复、对话历史管理</p>',
    '      <div class="suggestions">',
    '        <button onclick="quickQuestion(\'什么是 RAG 技术？\')">什么是 RAG 技术？</button>',
    '        <button onclick="quickQuestion(\'向量数据库有什么作用？\')">向量数据库有什么作用？</button>',
    '        <button onclick="quickQuestion(\'DeepSeek 是什么？\')">DeepSeek 是什么？</button>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div id="input-area">',
    '    <div class="input-row">',
    '      <textarea id="input" rows="1" placeholder="输入消息..." onkeydown="onInputKeydown(event)"></textarea>',
    '      <button id="send-btn" onclick="sendMessage()">发送</button>',
    '    </div>',
    '  </div>',
    '</div>',
    '<div id="notification-container"></div>',
    '',
    '<div class="confirm-overlay" id="confirm-overlay">',
    '  <div class="confirm-box">',
    '    <p id="confirm-text"></p>',
    '    <div class="confirm-btns">',
    '      <button class="btn-outline" onclick="hideConfirm()">取消</button>',
    '      <button class="btn-primary" id="confirm-yes-btn">确定</button>',
    '    </div>',
    '  </div>',
    '</div>',
    '',
    '<!-- KB Modal -->',
    '<div class="modal-overlay" id="kb-modal">',
    '  <div class="modal">',
    '    <div class="modal-header">',
    '      <h2>知识库管理</h2>',
    '      <button class="close-btn" onclick="hideKB()">&times;</button>',
    '    </div>',
    '    <div class="modal-body">',
    '      <div id="kb-loading" style="text-align:center;padding:40px;color:var(--text-secondary)">加载中...</div>',
    '      <div class="doc-list" id="doc-list" style="display:none"></div>',
    '      <div id="kb-empty" style="display:none;text-align:center;padding:40px;color:var(--text-secondary)">',
    '        暂无文档',
    '      </div>',
    '    </div>',
    '    <div class="modal-footer">',
    '      <label class="btn-primary" style="cursor:pointer;padding:10px 20px;border-radius:8px;display:inline-flex;align-items:center;gap:6px">',
    '        上传文件',
    '        <input type="file" accept=".md,.txt" style="display:none" onchange="uploadFile(this)">',
    '      </label>',
    '      <button class="btn-outline" onclick="hideKB()">关闭</button>',
    '    </div>',
    '  </div>',
    '</div>',
    '',
    '<!-- Rename Modal -->',
    '<div class="rename-overlay" id="rename-modal">',
    '  <div class="rename-box">',
    '    <h3>重命名对话</h3>',
    '    <input type="text" id="rename-input" onkeydown="if(event.key===\'Enter\')confirmRename()">',
    '    <div class="rename-btns">',
    '      <button class="btn-outline" onclick="hideRename()">取消</button>',
    '      <button class="btn-primary" onclick="confirmRename()">确定</button>',
    '    </div>',
    '  </div>',
    '</div>',
    '',
    '<script>',
    // ---- JAvaScript starts here ----
    'let currentConvId = null;',
    'let isStreaming = false;',
    'let adminToken = localStorage.getItem(\'admin_token\') || \'\';',
    'let confirmResolve = null;',
    'let welcomeHTML = \'\';',
    '',
    'const api = (path, opts) => fetch(path, { headers: { \'Content-Type\': \'application/json\', ...(opts?.headers || {}) }, ...opts });',
    '',
    '// Notifications',
    'function notify(msg, type) {',
    '  type = type || \'info\';',
    '  const c = document.getElementById(\'notification-container\');',
    '  const el = document.createElement(\'div\');',
    '  el.className = \'notification \' + type;',
    '  el.textContent = msg;',
    '  c.appendChild(el);',
    '  requestAnimationFrame(() => el.classList.add(\'show\'));',
    '  setTimeout(() => { el.classList.remove(\'show\'); setTimeout(() => el.remove(), 300); }, 3000);',
    '}',
    '',
    'function notifyConfirm(msg) {',
    '  return new Promise(resolve => {',
    '    confirmResolve = resolve;',
    '    document.getElementById(\'confirm-text\').textContent = msg;',
    '    document.getElementById(\'confirm-overlay\').classList.add(\'show\');',
    '    document.getElementById(\'confirm-yes-btn\').onclick = () => { hideConfirm(); resolve(true); };',
    '  });',
    '}',
    'function hideConfirm() {',
    '  document.getElementById(\'confirm-overlay\').classList.remove(\'show\');',
    '  if (confirmResolve) { confirmResolve(false); confirmResolve = null; }',
    '}',
    '',
    '// Dark Mode',
    'function toggleDarkMode() {',
    '  document.body.classList.toggle(\'dark\');',
    '  localStorage.setItem(\'dark\', document.body.classList.contains(\'dark\') ? \'1\' : \'\');',
    '}',
    'if (localStorage.getItem(\'dark\') === \'1\' || (window.matchMedia(\'(prefers-color-scheme:dark)\').matches && !localStorage.getItem(\'dark\'))) {',
    '  document.body.classList.add(\'dark\');',
    '}',
    '',
    '// Sidebar',
    'function toggleSidebar() {',
    '  document.getElementById(\'sidebar\').classList.toggle(\'open\');',
    '  document.getElementById(\'overlay\').classList.toggle(\'show\');',
    '}',
    '',
    '// Conversations',
    'async function loadConversations() {',
    '  try {',
    '    const list = await (await api(\'/api/conversations\')).json();',
    '    const container = document.getElementById(\'conv-list\');',
    '    container.innerHTML = list.map(function(c) {',
    '      var active = currentConvId === c.id ? \' active\' : \'\';',
    '      return \'<div class="conv-item\' + active + \'" onclick="switchConversation(\\\'\' + c.id + \'\\\')"><div class="conv-title">\' + esc(c.title) + \'</div><div class="conv-time">\' + fmt(c.updated_at) + \'</div><div class="conv-actions"><button onclick="event.stopPropagation();showRename(\\\'\' + c.id + \'\\\',\\\'\' + esc(c.title) + \'\\\')" title="重命名">&#9998;</button><button onclick="event.stopPropagation();deleteConv(\\\'\' + c.id + \'\\\')" title="删除">&#128465;</button></div></div>\';',
    '    }).join(\'\');',
    '  } catch(e) { console.error(e); }',
    '}',
    '',
    'async function newConversation() {',
    '  currentConvId = null;',
    '  document.getElementById(\'chat-title\').textContent = \'新对话\';',
    '  document.getElementById(\'messages\').innerHTML = welcomeHTML || \'<div class=\"welcome-msg\" id=\"welcome\"><h1>RAG Chatbot</h1><p>智能助手</p></div>\';',
    '  if (window.innerWidth < 768) toggleSidebar();',
    '  await loadConversations();',
    '}',
    '',
    'async function switchConversation(id) {',
    '  currentConvId = id;',
    '  try {',
    '    const msgs = await (await api(\'/api/conversations/\' + id)).json();',
    '    const title = document.querySelector(\'.conv-item.active .conv-title\');',
    '    document.getElementById(\'chat-title\').textContent = title ? title.textContent : \'对话\';',
    '    const container = document.getElementById(\'messages\');',
    '    container.innerHTML = msgs.map(m => renderMsg(m.role, m.content)).join(\'\');',
    '    container.scrollTop = container.scrollHeight;',
    '    if (window.innerWidth < 768) toggleSidebar();',
    '    await loadConversations();',
    '  } catch(e) { console.error(e); }',
    '}',
    '',
    'async function deleteConv(id) {',
    '  const ok = await notifyConfirm(\'确定删除该对话？\');',
    '  if (!ok) return;',
    '  try {',
    '    await api(\'/api/conversations/\' + id, { method: \'DELETE\' });',
    '    if (currentConvId === id) newConversation();',
    '    else await loadConversations();',
    '    notify(\'已删除\', \'success\');',
    '  } catch(e) { notify(\'删除失败\', \'error\'); }',
    '}',
    '',
    'let renameId = null;',
    'function showRename(id, title) {',
    '  renameId = id;',
    '  document.getElementById(\'rename-input\').value = title;',
    '  document.getElementById(\'rename-modal\').classList.add(\'show\');',
    '  setTimeout(() => document.getElementById(\'rename-input\').focus(), 100);',
    '}',
    'function hideRename() {',
    '  document.getElementById(\'rename-modal\').classList.remove(\'show\');',
    '  renameId = null;',
    '}',
    'async function confirmRename() {',
    '  const title = document.getElementById(\'rename-input\').value.trim();',
    '  if (!title || !renameId) return;',
    '  try {',
    '    await api(\'/api/conversations/\' + renameId, { method: \'PUT\', body: JSON.stringify({ title }) });',
    '    hideRename();',
    '    await loadConversations();',
    '    if (currentConvId === renameId) document.getElementById(\'chat-title\').textContent = title;',
    '    notify(\'已重命名\', \'success\');',
    '  } catch(e) { notify(\'重命名失败\', \'error\'); }',
    '}',
    '',
    'function filterConversations(q) {',
    '  document.querySelectorAll(\'.conv-item\').forEach(el => {',
    '    const t = el.querySelector(\'.conv-title\').textContent.toLowerCase();',
    '    el.style.display = t.includes(q.toLowerCase()) ? \'\' : \'none\';',
    '  });',
    '}',
    '',
    '// Chat',
    'function quickQuestion(q) {',
    '  document.getElementById(\'input\').value = q;',
    '  sendMessage();',
    '}',
    'function onInputKeydown(e) {',
    '  if (e.key === \'Enter\' && !e.shiftKey) { e.preventDefault(); sendMessage(); }',
    '}',
    '',
    'async function sendMessage() {',
    '  const input = document.getElementById(\'input\');',
    '  const msg = input.value.trim();',
    '  if (!msg || isStreaming) return;',
    '  input.value = \'\';',
    '  input.style.height = \'auto\';',
    '  isStreaming = true;',
    '  const container = document.getElementById(\'messages\');',
    '  const welcome = container.querySelector(\'.welcome-msg\');',
    '  if (welcome) container.innerHTML = \'\';',
    '  container.appendChild(msgEl(\'user\', msg));',
    '  container.scrollTop = container.scrollHeight;',
    '  const adiv = msgEl(\'assistant\', \'\', true);',
    '  container.appendChild(adiv);',
    '  const bubble = adiv.querySelector(\'.bubble\');',
    '  document.getElementById(\'send-btn\').disabled = true;',
    '  try {',
    '    const res = await fetch(\'/chat/stream\', {',
    '      method: \'POST\',',
    '      headers: { \'Content-Type\': \'application/json\' },',
    '      body: JSON.stringify({ message: msg, conversation_id: currentConvId })',
    '    });',
    '    if (!res.ok) throw new Error(\'HTTP \' + res.status);',
    '    const reader = res.body.getReader();',
    '    const dec = new TextDecoder();',
    '    let buf = \'\', full = \'\';',
    '    while (true) {',
    '      const { done, value } = await reader.read();',
    '      if (done) break;',
    '      buf += dec.decode(value, { stream: true });',
    '      const lines = buf.split(\'\\n\');',
    '      buf = lines.pop() || \'\';',
    '      for (const l of lines) {',
    '        if (!l.trim()) continue;',
    '        try {',
    '          const data = JSON.parse(l);',
    '          if (data.type === \'chunk\') {',
    '            full += data.content;',
    '            bubble.innerHTML = marked.parse(full);',
    '            container.scrollTop = container.scrollHeight;',
    '          } else if (data.type === \'done\') {',
    '            currentConvId = data.conversation_id;',
    '            document.getElementById(\'chat-title\').textContent = msg.slice(0, 50);',
    '            if (data.sources && data.sources.length > 0) {',
    '              bubble.innerHTML += \'<div style="margin-top:12px;padding-top:12px;border-top:1px solid var(--border);font-size:12px;color:var(--text-secondary)"><strong>参考:</strong> \' + data.sources.map(s => esc(s.title || s.source || s)).join(\', \') + \'</div>\';',
    '            }',
    '            await loadConversations();',
    '          } else if (data.type === \'error\') {',
    '            bubble.innerHTML = \'<span style="color:#dc2626">错误: \' + esc(data.error) + \'</span>\';',
    '          }',
    '        } catch(e) {}',
    '      }',
    '    }',
    '  } catch(e) {',
    '    bubble.innerHTML = \'<span style="color:#dc2626">请求失败: \' + esc(e.message) + \'</span>\';',
    '  } finally {',
    '    isStreaming = false;',
    '    document.getElementById(\'send-btn\').disabled = false;',
    '    input.focus();',
    '  }',
    '}',
    '',
    'function msgEl(role, content, loading) {',
    '  const div = document.createElement(\'div\');',
    '  div.className = \'message \' + role;',
    '  if (loading) {',
    '    div.innerHTML = \'<div class="bubble"><div class="typing"><span></span><span></span><span></span></div></div>\';',
    '  } else if (role === \'assistant\') {',
    '    div.innerHTML = \'<div class="bubble">\' + marked.parse(content) + \'</div>\';',
    '  } else {',
    '    div.innerHTML = \'<div class="bubble">\' + esc(content) + \'</div>\';',
    '  }',
    '  return div;',
    '}',
    '',
    'function renderMsg(role, content) {',
    '  if (role === \'assistant\') {',
    '    return \'<div class="message assistant"><div class="bubble">\' + marked.parse(content) + \'</div></div>\';',
    '  }',
    '  return \'<div class="message user"><div class="bubble">\' + esc(content) + \'</div></div>\';',
    '}',
    '',
    '// Knowledge Base',
    'function showKB() {',
    '  document.getElementById(\'kb-modal\').classList.add(\'show\');',
    '  (async () => {',
    '    try {',
    '      const docs = await (await fetch(\'/api/documents\', { headers: { \'authorization\': \'Bearer \' + adminToken } })).json();',
    '      document.getElementById(\'kb-loading\').style.display = \'none\';',
    '      if (docs.length === 0) {',
    '        document.getElementById(\'kb-empty\').style.display = \'\';',
    '        return;',
    '      }',
    '      const list = document.getElementById(\'doc-list\');',
    '      list.style.display = \'\';',
    '      list.innerHTML = docs.map(d => \'<div class="doc-item"><div class="doc-info"><div class="doc-name">\' + esc(d.filename) + \'</div><div class="doc-meta">\' + d.chunk_count + \' 个分块 | \' + fmt(d.created_at) + \'</div></div><button class="doc-del" onclick="deleteDoc(\\\'\' + d.id + \'\\\')">&#10005;</button></div>\').join(\'\');',
    '    } catch(e) {',
    '      document.getElementById(\'kb-loading\').style.display = \'none\';',
    '      notify(\'加载失败\', \'error\');',
    '    }',
    '  })();',
    '}',
    'function hideKB() { document.getElementById(\'kb-modal\').classList.remove(\'show\'); }',
    '',
    'async function uploadFile(input) {',
    '  const file = input.files[0];',
    '  if (!file) return;',
    '  const list = document.getElementById(\'doc-list\');',
    '  const empty = document.getElementById(\'kb-empty\');',
    '  const loading = document.getElementById(\'kb-loading\');',
    '  loading.style.display = \'none\'; empty.style.display = \'none\'; list.style.display = \'\';',
    '  const le = document.createElement(\'div\');',
    '  le.className = \'doc-loading\';',
    '  le.innerHTML = \'<div class="spinner"></div> 正在上传 \' + esc(file.name) + \'...\';',
    '  list.insertBefore(le, list.firstChild);',
    '  const form = new FormData(); form.append(\'file\', file);',
    '  try {',
    '    const res = await fetch(\'/api/documents/upload\', { method: \'POST\', headers: { \'authorization\': \'Bearer \' + adminToken }, body: form });',
    '    const data = await res.json();',
    '    le.remove();',
    '    if (data.ok) { notify(\'上传成功: \' + data.chunkCount + \' 个分块\', \'success\'); input.value = \'\'; showKB(); }',
    '    else { notify(\'上传失败: \' + (data.error || \'unknown\'), \'error\'); }',
    '  } catch(e) { le.remove(); notify(\'上传失败\', \'error\'); }',
    '}',
    '',
    'async function deleteDoc(id) {',
    '  const ok = await notifyConfirm(\'确定删除该文档？\');',
    '  if (!ok) return;',
    '  try {',
    '    await fetch(\'/api/documents/\' + id, { method: \'DELETE\', headers: { authorization: \'Bearer \' + adminToken } });',
    '    notify(\'已删除\', \'success\');',
    '    showKB();',
    '  } catch(e) { notify(\'删除失败\', \'error\'); }',
    '}',
    '',
    '// Utils',
    'function esc(s) { if (!s) return \'\'; return s.replace(/&/g,\'&amp;\').replace(/</g,\'&lt;\').replace(/>/g,\'&gt;\'); }',
    'function fmt(t) {',
    '  try {',
    '    const d = new Date(t); const n = new Date(); const diff = n - d;',
    '    if (diff < 60000) return \'刚刚\';',
    '    if (diff < 3600000) return Math.floor(diff/60000) + \' 分钟前\';',
    '    if (diff < 86400000) return Math.floor(diff/3600000) + \' 小时前\';',
    '    return d.toLocaleDateString(\'zh-CN\', { month: \'short\', day: \'numeric\' });',
    '  } catch(e) { return t; }',
    '}',
    '',
    '// Init',
    'window.addEventListener(\'DOMContentLoaded\', () => {',
    '  const wel = document.getElementById(\'welcome\');',
    '  if (wel) welcomeHTML = wel.outerHTML;',
    '});',
    'if (\'serviceWorker\' in navigator) {',
    '  navigator.serviceWorker.register(\'/sw.js\').catch(()=>{});',
    '}',
    'loadConversations();',
    'document.getElementById(\'input\').addEventListener(\'input\', function() {',
    '  this.style.height = \'auto\';',
    '  this.style.height = Math.min(this.scrollHeight, 150) + \'px\';',
    '});',
    '</script>',
    '</body>',
    '</html>',
  ].join('\n');
}

// helper: create opening tag
function ko(tag: string): string {
  return '<' + tag + '>';
}
